import test from 'node:test'
import assert from 'node:assert/strict'
import { aggregateSimulations, chooseAutoMove, classifyDifficulty, compareDifficultyTarget, playLevel, scoreCandidate, simulateLevels } from '../src/match3/autoplayer.js'
import { createGame, legalMoves, swap } from '../src/match3/engine.js'
import { MATCH3_LEVELS, validateMatch3Levels } from '../src/match3/levels.js'
test('auto-player output is deterministic',()=>assert.deepEqual(playLevel(MATCH3_LEVELS[0],{seed:42,strategy:'objective-aware'}),playLevel(MATCH3_LEVELS[0],{seed:42,strategy:'objective-aware'})))
test('every strategy selects a legal move',()=>{const state=createGame(MATCH3_LEVELS[0],9),legal=legalMoves(state.board).map(JSON.stringify);for(const strategy of ['random-legal','greedy-score','objective-aware'])assert.ok(legal.includes(JSON.stringify(chooseAutoMove(state,{strategy,seed:2}))))})
test('objective-aware scoring prioritises objective progress',()=>{const state=createGame(MATCH3_LEVELS[1],5),moves=legalMoves(state.board),outcomes=moves.map(move=>swap(state,move.from,move.to).state),best=[...outcomes].sort((a,b)=>scoreCandidate(state,b,'objective-aware')-scoreCandidate(state,a,'objective-aware')).at(-1);assert.ok((best.progress.collected.sun??0)>=0);assert.ok(scoreCandidate(state,best,'objective-aware')>=Math.min(...outcomes.map(x=>scoreCandidate(state,x,'objective-aware'))))})
test('seeded simulations reproduce exactly',()=>assert.deepEqual(simulateLevels(MATCH3_LEVELS.slice(0,2),{runs:3,seed:7}),simulateLevels(MATCH3_LEVELS.slice(0,2),{runs:3,seed:7})))
test('safety limit terminates play',()=>{const result=playLevel(MATCH3_LEVELS[19],{seed:1,safetyLimit:1});assert.equal(result.movesUsed,1);assert.equal(result.failureReason,'safety-limit')})
test('aggregation calculates win rate, median and bottleneck',()=>{const base={levelId:1,strategy:'basic',movesUsed:5,remainingMoves:3,score:100,powerUpsUsed:{},deadBoardShuffles:0,cascadeCount:2,longestCascade:1};const result=aggregateSimulations([{...base,won:true,status:'won',failureReason:null,bottleneck:null},{...base,movesUsed:9,won:false,status:'lost',failureReason:'moves-exhausted',bottleneck:{type:'score'}}]);assert.equal(result.winRate,.5);assert.equal(result.medianMovesUsed,7);assert.equal(result.difficultyBand,'Medium');assert.equal(result.objectiveBottlenecks.score,1)})
test('difficulty classification follows provisional thresholds',()=>{assert.equal(classifyDifficulty(.9),'Tutorial');assert.equal(classifyDifficulty(.8),'Easy');assert.equal(classifyDifficulty(.6),'Medium');assert.equal(classifyDifficulty(.3),'Hard');assert.equal(classifyDifficulty(.1),'Showcase')})
test('difficulty target comparison reports above, within and below',()=>{assert.equal(compareDifficultyTarget(1,'Tutorial'),'above');assert.equal(compareDifficultyTarget(.8,'Easy'),'within');assert.equal(compareDifficultyTarget(.1,'Hard'),'below')})
test('level tuning validation rejects invalid edits',()=>assert.ok(validateMatch3Levels([{...MATCH3_LEVELS[0],moves:0}]).length))
