import styles from './AboutUs.module.css'
import BottomNav from '../components/BottomNav'

export default function AboutUs({ onBack, navProps }) {
  return (
    <div className={styles.page}>
      <div className={styles.header}>
        <button className={styles.backBtn} onClick={onBack} aria-label="Back">
          <img src="/images/back_button.webp" alt="Back" draggable="false" className={styles.backBtnImg} />
        </button>
        <h1 className={styles.title}>About Us</h1>
      </div>

      <div className={styles.content}>

        <div className={styles.logoWrap}>
          <img src="/images/mascot3b.webp" alt="Flip Out! mascot" draggable="false" className={styles.mascot} />
          <div className={styles.appName}>Flip Out!</div>
          <div className={styles.appTagline}>The ultimate card-matching showdown</div>
        </div>

        <div className={styles.card}>
          <div className={styles.cardTitle}>WHO WE ARE</div>
          <p className={styles.cardText}>
            Gizmo Games is a UK-based Community Interest Company (CIC). Every penny
            generated by our games goes directly towards funding our mission.
          </p>
        </div>

        <div className={styles.card}>
          <div className={styles.cardTitle}>OUR MISSION</div>
          <p className={styles.cardText} style={{ fontStyle: 'italic', color: 'rgba(255,255,255,0.9)' }}>
            "When I was at my absolute lowest, these little creatures saved me.
            Now I want to do the same for as many of them as I can."
          </p>
          <p className={styles.cardText} style={{ marginTop: 8 }}>
            We are working to establish a cat sanctuary and free veterinary service
            for local residents who cannot afford care elsewhere. When you play Flip Out!,
            buy a deck, or support us in any way — you're helping make that happen.
          </p>
          <p className={styles.cardText} style={{ marginTop: 8 }}>
            🐱 Every game played. Every purchase made. Every cat helped.
          </p>
        </div>

        <div className={styles.card}>
          <div className={styles.cardTitle}>FLIP OUT!</div>
          <p className={styles.cardText}>
            Flip Out! is a memory card-matching game with a twist — special power cards
            shake up every round with abilities like the Stopwatch, Freeze, Rocket,
            Tornado and more. Challenge the AI, battle through the Gauntlet, or go
            head-to-head with a friend online in real-time multiplayer.
          </p>
        </div>

        <div className={styles.card}>
          <div className={styles.cardTitle}>CONTACT US</div>
          <p className={styles.cardText}>
            We'd love to hear from you — questions, feedback or support requests are all welcome.
          </p>
          <a href="mailto:support@gizmogames.uk" className={styles.emailLink}>
            support@gizmogames.uk
          </a>
        </div>

        <div className={styles.createdBy}>
          <span className={styles.createdByText}>Created by</span>
          <img src="/images/gg.webp" alt="Gizmo Games" draggable="false" className={styles.createdByLogo} />
          <div className={styles.copyright}>© 2026 Gizmo Games. All rights reserved.</div>
        </div>

      </div>

      <BottomNav active="settings" {...navProps} />
    </div>
  )
}
