import { MATCH3_TOKENS } from './levels.js'

export function seededRandom(seed = 1) { let x = Number(seed) >>> 0 || 1; return () => ((x = Math.imul(1664525, x) + 1013904223 >>> 0) / 4294967296) }
const key = (r,c) => `${r}:${c}`
const clone = state => structuredClone(state)
const adjacent = (a,b) => Math.abs(a.r-b.r)+Math.abs(a.c-b.c) === 1
const usable = cell => cell && !cell.hole
const movable = cell => usable(cell) && !cell.chain && !cell.crate && cell.token && !cell.drop

function runs(board) {
  const found=[]; const rows=board.length, cols=board[0].length
  for (let r=0;r<rows;r++) for (let c=0;c<cols;) { const t=board[r][c]?.token; let e=c+1; while(t && e<cols && board[r][e]?.token===t)e++; if(t&&e-c>=3)found.push(Array.from({length:e-c},(_,i)=>({r,c:c+i}))); c=e }
  for (let c=0;c<cols;c++) for (let r=0;r<rows;) { const t=board[r][c]?.token; let e=r+1; while(t && e<rows && board[e][c]?.token===t)e++; if(t&&e-r>=3)found.push(Array.from({length:e-r},(_,i)=>({r:r+i,c}))); r=e }
  return found
}
export function findMatches(board) { const groups=runs(board), map=new Map(); for(const g of groups) for(const p of g){ const k=key(p.r,p.c); const old=map.get(k)??{...p,token:board[p.r][p.c].token,horizontal:0,vertical:0}; if(g[0].r===g.at(-1).r)old.horizontal=Math.max(old.horizontal,g.length); else old.vertical=Math.max(old.vertical,g.length); map.set(k,old) } return { groups, cells:[...map.values()] } }
export function legalMoves(board) { const out=[]; for(let r=0;r<board.length;r++)for(let c=0;c<board[0].length;c++)for(const b of [{r,c:c+1},{r:r+1,c}])if(b.r<board.length&&b.c<board[0].length&&movable(board[r][c])&&movable(board[b.r][b.c])){[board[r][c],board[b.r][b.c]]=[board[b.r][b.c],board[r][c]];const valid=findMatches(board).cells.length>0;[board[r][c],board[b.r][b.c]]=[board[b.r][b.c],board[r][c]];if(valid)out.push({from:{r,c},to:b})} return out }

function randomToken(rng) { return MATCH3_TOKENS[Math.floor(rng()*MATCH3_TOKENS.length)].id }
function baseBoard(level,rng) { const holes=new Set((level.holes??[]).map(p=>key(...p))); const board=Array.from({length:level.rows},(_,r)=>Array.from({length:level.cols},(_,c)=>holes.has(key(r,c))?{hole:true}:{token:null,special:null,ice:0,chain:0,crate:0,drop:false})); for(const b of level.blockers??[])for(const [r,c]of b.cells)board[r][c][b.type]=b.layer??1; for(const [r,c]of level.drops??[])board[r][c].drop=true; for(let r=0;r<level.rows;r++)for(let c=0;c<level.cols;c++)if(usable(board[r][c])&&!board[r][c].drop&&!board[r][c].crate){let t; do{t=randomToken(rng);board[r][c].token=t}while((c>1&&board[r][c-1]?.token===t&&board[r][c-2]?.token===t)||(r>1&&board[r-1][c]?.token===t&&board[r-2][c]?.token===t))} return board }
export function generateBoard(level,seed=1) { const rng=seededRandom(seed); for(let i=0;i<100;i++){const board=baseBoard(level,rng); if(!findMatches(board).cells.length&&legalMoves(board).length)return board} throw new Error('Unable to create playable board') }
function chooseSpecial(matches, preferred) { const hit=matches.cells.find(p=>p.r===preferred?.r&&p.c===preferred?.c)??matches.cells[0]; if(matches.cells.some(p=>p.horizontal>=3&&p.vertical>=3))return {at:hit,type:'bomb'}; const max=Math.max(...matches.cells.flatMap(p=>[p.horizontal,p.vertical])); if(max>=5)return {at:hit,type:'color'}; if(max===4)return {at:hit,type:hit.horizontal===4?'row':'col'}; return null }
function specialCells(board,p) { const cell=board[p.r][p.c]; if(cell.special==='row')return board[p.r].map((_,c)=>({r:p.r,c})); if(cell.special==='col')return board.map((_,r)=>({r,c:p.c})); if(cell.special==='bomb'){const a=[];for(let r=p.r-1;r<=p.r+1;r++)for(let c=p.c-1;c<=p.c+1;c++)if(board[r]?.[c])a.push({r,c});return a} return [p] }
function damage(board,targets,progress) { const queue=[...targets], seen=new Set(); while(queue.length){const p=queue.pop(),k=key(p.r,p.c);if(seen.has(k)||!usable(board[p.r]?.[p.c]))continue;seen.add(k);const cell=board[p.r][p.c]; if(cell.special&&cell.special!=='color')queue.push(...specialCells(board,p)); if(cell.crate){cell.crate--;progress.blockers++;continue} if(cell.ice){cell.ice--;progress.blockers++} if(cell.chain){cell.chain--;progress.blockers++} if(cell.token){progress.collected[cell.token]=(progress.collected[cell.token]??0)+1;cell.token=null;cell.special=null;for(const n of [{r:p.r-1,c:p.c},{r:p.r+1,c:p.c},{r:p.r,c:p.c-1},{r:p.r,c:p.c+1}])if(board[n.r]?.[n.c]?.crate)queue.push(n)} } return seen.size }
function gravity(board,rng,progress) { const rows=board.length,cols=board[0].length; for(let c=0;c<cols;c++){const slots=[];for(let r=rows-1;r>=0;r--)if(usable(board[r][c])&&!board[r][c].crate)slots.push(r);const values=[];for(const r of slots)if(board[r][c].drop||board[r][c].token)values.push({token:board[r][c].token,special:board[r][c].special,drop:board[r][c].drop});for(const r of slots){const v=values.shift()??{token:randomToken(rng),special:null,drop:false};board[r][c].token=v.token;board[r][c].special=v.special;board[r][c].drop=v.drop}const bottom=slots[0];if(bottom!=null&&board[bottom][c].drop){board[bottom][c].drop=false;board[bottom][c].token=randomToken(rng);progress.drops++}} }
export function resolveBoard(state, preferred) { const s=clone(state),rng=seededRandom(s.rngState++), cascades=[]; for(let n=0;n<50;n++){const m=findMatches(s.board);if(!m.cells.length)break;const made=chooseSpecial(m,n===0?preferred:null);const targets=m.cells.map(({r,c})=>({r,c}));const cleared=damage(s.board,targets,s.progress);if(made&&usable(s.board[made.at.r][made.at.c])){s.board[made.at.r][made.at.c].token=m.cells[0].token;s.board[made.at.r][made.at.c].special=made.type}s.score+=cleared*50*(n+1);gravity(s.board,rng,s.progress);cascades.push({cleared,special:made?.type??null})} if(cascades.length>=50)throw new Error('Cascade limit exceeded'); if(!legalMoves(s.board).length){s.board=shuffleBoard(s.board,s.rngState++);s.analytics.push({type:'dead-board-shuffle'})} s.cascades=cascades;updateStatus(s);return s }
export function shuffleBoard(board,seed=1) { const rng=seededRandom(seed),cells=[];for(const row of board)for(const c of row)if(movable(c))cells.push(c.token);for(let attempt=0;attempt<100;attempt++){const copy=clone(board),pool=[...cells];for(let i=pool.length-1;i;i--){const j=Math.floor(rng()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}let i=0;for(const row of copy)for(const c of row)if(movable(c))c.token=pool[i++];if(!findMatches(copy).cells.length&&legalMoves(copy).length)return copy}throw new Error('Unable to shuffle dead board') }
function objectiveDone(s,o){if(o.type==='score')return s.score>=o.target;if(o.type==='collect')return(s.progress.collected[o.token]??0)>=o.target;if(o.type==='blockers')return s.progress.blockers>=o.target;if(o.type==='drops')return s.progress.drops>=o.target;return false}
function updateStatus(s){if(s.level.objectives.every(o=>objectiveDone(s,o)))s.status='won';else if(s.movesRemaining<=0)s.status='lost';else s.status='active'}
export function createGame(level,seed=1){return{version:1,level,seed,rngState:seed+1,board:generateBoard(level,seed),score:0,movesRemaining:level.moves,progress:{collected:{},blockers:0,drops:0},status:'active',cascades:[],usedActions:[],analytics:[]}}
export function swap(state,from,to){if(state.status!=='active'||!adjacent(from,to)||!movable(state.board[from.r]?.[from.c])||!movable(state.board[to.r]?.[to.c]))return{state,accepted:false};const s=clone(state),a=s.board[from.r][from.c],b=s.board[to.r][to.c];[s.board[from.r][from.c],s.board[to.r][to.c]]=[b,a];const special=a.special||b.special;if(!special&&!findMatches(s.board).cells.length)return{state,accepted:false};s.movesRemaining--;if(a.special==='color'||b.special==='color'){const color=a.special==='color'?b.token:a.token;const targets=[];for(let r=0;r<s.board.length;r++)for(let c=0;c<s.board[0].length;c++)if(s.board[r][c]?.token===color)targets.push({r,c});damage(s.board,targets,s.progress);gravity(s.board,seededRandom(s.rngState++),s.progress)}else if(a.special&&b.special){damage(s.board,[...specialCells(s.board,from),...specialCells(s.board,to)],s.progress);gravity(s.board,seededRandom(s.rngState++),s.progress)}return{state:resolveBoard(s,to),accepted:true}}
export function applyPowerUp(state,type,target){if(state.status!=='active'&&!(state.status==='lost'&&type==='extra-moves'))return{state,applied:false};const s=clone(state),cell=target?s.board[target.r]?.[target.c]:null;if(type==='extra-moves'){s.movesRemaining+=5;s.status='active';return{state:s,applied:true}}if(type==='shuffle'){s.board=shuffleBoard(s.board,s.rngState++);return{state:s,applied:true}}if(!usable(cell))return{state,applied:false};let targets=[];if(type==='hammer'){if(!cell.token&&!cell.crate&&!cell.ice&&!cell.chain)return{state,applied:false};targets=[target]}else if(type==='line-blast')targets=s.board[target.r].map((_,c)=>({r:target.r,c}));else if(type==='color-clear'){if(!cell.token)return{state,applied:false};for(let r=0;r<s.board.length;r++)for(let c=0;c<s.board[0].length;c++)if(s.board[r][c]?.token===cell.token)targets.push({r,c})}else return{state,applied:false};damage(s.board,targets,s.progress);gravity(s.board,seededRandom(s.rngState++),s.progress);return{state:resolveBoard(s,target),applied:true}}
export function objectiveProgress(state,o){if(o.type==='score')return Math.min(state.score,o.target);if(o.type==='collect')return Math.min(state.progress.collected[o.token]??0,o.target);return Math.min(state.progress[o.type]??0,o.target)}
