import crypto from 'node:crypto'
import { applyReward, enforceRateLimit } from './_gameServices.js'
import { appendCoinTransaction } from './_coinLedger.js'
import { MATCH3_LEVELS, getMatch3Level } from '../src/match3/levels.js'
import { applyPowerUp, createGame, swap } from '../src/match3/engine.js'

export const MATCH3_POWERUPS = Object.freeze({ hammer:'powerup:match3-hammer', shuffle:'powerup:match3-shuffle', 'line-blast':'powerup:match3-line-blast', 'color-clear':'powerup:match3-color-clear', 'extra-moves':'powerup:match3-extra-moves' })
export const MATCH3_BASE_COIN_REWARD = 10
export const MATCH3_ADVERT_COIN_BONUS = 10
const safeId = (value,label='id') => { if(!/^[a-z0-9][a-z0-9:_-]{0,127}$/i.test(String(value??'')))throw Object.assign(new Error(`Invalid ${label}`),{status:400});return String(value) }

function publicSession(row) { return { sessionId:row.session_id, levelId:Number(row.level_id), status:row.status, state:row.state, baseRewardGranted:row.base_stars_granted, advertRewardGranted:row.advert_stars_granted, baseStarsGranted:row.base_stars_granted, advertStarsGranted:row.advert_stars_granted, updatedAt:row.updated_at } }
async function owned(client,playerId,sessionId,lock=true){const q=await client.query(`SELECT * FROM fo_match3_sessions WHERE session_id=$1 AND player_id=$2${lock?' FOR UPDATE':''}`,[sessionId,playerId]);if(!q.rowCount)throw Object.assign(new Error('Match-3 session not found'),{status:404});return q.rows[0]}
async function priorAction(client,{actionId,playerId}){const q=await client.query(`SELECT player_id,result FROM fo_match3_actions WHERE action_id=$1`,[actionId]);if(!q.rowCount)return null;if(String(q.rows[0].player_id)!==String(playerId))throw Object.assign(new Error('Action belongs to another account'),{status:403});return q.rows[0].result}
async function saveAction(client,{row,playerId,actionId,type,state,result={}}){await client.query(`UPDATE fo_match3_sessions SET state=$2,status=$3,updated_at=NOW(),completed_at=CASE WHEN $3='won' THEN COALESCE(completed_at,NOW()) ELSE completed_at END WHERE session_id=$1`,[row.session_id,state,state.status]);const value={...result,session:{sessionId:row.session_id,levelId:Number(row.level_id),status:state.status,state}};await client.query(`INSERT INTO fo_match3_actions(action_id,session_id,player_id,action_type,result) VALUES($1,$2,$3,$4,$5)`,[actionId,row.session_id,playerId,type,value]);return value}

export async function getMatch3State(db,{playerId,sessionId}){if(sessionId){const row=await owned(db,playerId,sessionId,false);return{session:publicSession(row)}}const [progress,active]=await Promise.all([db.query(`SELECT highest_unlocked_level,completed_levels FROM fo_match3_progress WHERE player_id=$1`,[playerId]),db.query(`SELECT * FROM fo_match3_sessions WHERE player_id=$1 AND status='active' ORDER BY updated_at DESC LIMIT 1`,[playerId])]);return{levels:MATCH3_LEVELS.map(({id,name,moves,objectives,teaching})=>({id,name,moves,objectives,teaching})),progress:progress.rows[0]??{highest_unlocked_level:1,completed_levels:{}},resume:active.rowCount?publicSession(active.rows[0]):null}}
export async function startMatch3(db,{playerId,levelId,requestId}){const level=getMatch3Level(levelId);if(!level)throw Object.assign(new Error('Unknown level'),{status:400});const sessionId=safeId(requestId??`match3:${crypto.randomUUID()}`,'session id'),client=await db.connect();try{await client.query('BEGIN');await enforceRateLimit(client,{playerId,action:'match3-start',limit:20});const prior=await client.query(`SELECT * FROM fo_match3_sessions WHERE session_id=$1`,[sessionId]);if(prior.rowCount){if(String(prior.rows[0].player_id)!==String(playerId))throw Object.assign(new Error('Session belongs to another account'),{status:403});await client.query('COMMIT');return{duplicate:true,session:publicSession(prior.rows[0])}}await client.query(`INSERT INTO fo_match3_progress(player_id) VALUES($1) ON CONFLICT DO NOTHING`,[playerId]);const unlocked=await client.query(`SELECT highest_unlocked_level FROM fo_match3_progress WHERE player_id=$1 FOR UPDATE`,[playerId]);if(Number(levelId)>Number(unlocked.rows[0].highest_unlocked_level)&&process.env.VERCEL_ENV==='production')throw Object.assign(new Error('Level is locked'),{status:403});const seed=crypto.randomInt(1,2147483647),state=createGame(level,seed);await client.query(`INSERT INTO fo_match3_sessions(session_id,player_id,level_id,seed,state) VALUES($1,$2,$3,$4,$5)`,[sessionId,playerId,level.id,seed,state]);await client.query('COMMIT');return{duplicate:false,session:{sessionId,levelId:level.id,status:'active',state}}}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
export async function moveMatch3(db,{playerId,sessionId,actionId,from,to}){actionId=safeId(actionId,'action id');const client=await db.connect();try{await client.query('BEGIN');const old=await priorAction(client,{actionId,playerId});if(old){await client.query('COMMIT');return{...old,duplicate:true}}const row=await owned(client,playerId,sessionId);const moved=swap(row.state,from,to);if(!moved.accepted)throw Object.assign(new Error('Swap does not create a match'),{status:409,code:'INVALID_SWAP'});const result=await saveAction(client,{row,playerId,actionId,type:'move',state:moved.state,result:{accepted:true}});await client.query('COMMIT');return{...result,duplicate:false}}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
export async function applyMatch3PowerUp(db,{playerId,sessionId,actionId,powerUp,target}){actionId=safeId(actionId,'action id');const itemId=MATCH3_POWERUPS[powerUp];if(!itemId)throw Object.assign(new Error('Unknown power-up'),{status:400});const client=await db.connect();try{await client.query('BEGIN');const old=await priorAction(client,{actionId,playerId});if(old){await client.query('COMMIT');return{...old,duplicate:true}}const row=await owned(client,playerId,sessionId);const applied=applyPowerUp(row.state,powerUp,target);if(!applied.applied)throw Object.assign(new Error('Power-up cannot be applied here'),{status:409,code:'POWERUP_NOT_APPLICABLE'});const unlimited=process.env.VERCEL_ENV!=='production'&&process.env.MATCH3_UNLIMITED_POWERUPS==='true';if(!unlimited)await applyReward(client,{playerId,transactionId:`match3-power:${actionId}`,source:'match3-power-up',reward:{itemId,amount:-1},metadata:{sessionId,actionId}});applied.state.analytics.push({type:'power-up-used',powerUp});const result=await saveAction(client,{row,playerId,actionId,type:`power-up:${powerUp}`,state:applied.state,result:{powerUp,unlimited}});await client.query('COMMIT');return{...result,duplicate:false}}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
export async function restartMatch3(db,{playerId,sessionId,actionId}){actionId=safeId(actionId,'action id');const client=await db.connect();try{await client.query('BEGIN');const old=await priorAction(client,{actionId,playerId});if(old){await client.query('COMMIT');return{...old,duplicate:true}}const row=await owned(client,playerId,sessionId),state=createGame(getMatch3Level(row.level_id),Number(row.seed)+1);const result=await saveAction(client,{row,playerId,actionId,type:'restart',state});await client.query('COMMIT');return result}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
export async function completeMatch3(db,{playerId,sessionId}){const client=await db.connect();try{await client.query('BEGIN');const row=await owned(client,playerId,sessionId);if(row.state.status!=='won')throw Object.assign(new Error('Level has not been completed'),{status:409});const tx=`match3-complete:${sessionId}`;const granted=await appendCoinTransaction(client,{accountId:playerId,transactionId:tx,amount:MATCH3_BASE_COIN_REWARD,transactionType:'promotional-grant',sourceReferenceId:sessionId,metadata:{source:'match3-completion',sessionId,levelId:row.level_id,score:row.state.score},allowCreation:true});const next=Math.min(20,Number(row.level_id)+1);await client.query(`INSERT INTO fo_match3_progress(player_id,highest_unlocked_level,completed_levels) VALUES($1,$2,jsonb_build_object($3::text,jsonb_build_object('coins',$4::int,'score',$5::int))) ON CONFLICT(player_id) DO UPDATE SET highest_unlocked_level=GREATEST(fo_match3_progress.highest_unlocked_level,$2),completed_levels=fo_match3_progress.completed_levels||jsonb_build_object($3::text,jsonb_build_object('coins',$4::int,'score',$5::int)),updated_at=NOW()`,[playerId,next,row.level_id,MATCH3_BASE_COIN_REWARD,row.state.score]);await client.query(`UPDATE fo_match3_sessions SET base_stars_granted=TRUE WHERE session_id=$1`,[sessionId]);await client.query('COMMIT');return{duplicate:granted.duplicate,coinsGranted:MATCH3_BASE_COIN_REWARD,totalCoins:MATCH3_BASE_COIN_REWARD,reward:{currencyId:'coins',amount:MATCH3_BASE_COIN_REWARD},transactionId:tx}}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
export async function doubleMatch3Coins(db,{playerId,sessionId,advertCompletionId}){const client=await db.connect();try{await client.query('BEGIN');const row=await owned(client,playerId,sessionId);if(!row.base_stars_granted)throw Object.assign(new Error('Base completion must be claimed first'),{status:409});const tx=`match3-double:${sessionId}`,prior=await client.query(`SELECT transaction_id FROM fo_player_transactions WHERE transaction_id=$1`,[tx]);if(prior.rowCount){await client.query('COMMIT');return{duplicate:true,coinsGranted:MATCH3_ADVERT_COIN_BONUS,totalCoins:MATCH3_BASE_COIN_REWARD+MATCH3_ADVERT_COIN_BONUS,reward:{currencyId:'coins',amount:MATCH3_ADVERT_COIN_BONUS},transactionId:tx}}const ad=await client.query(`DELETE FROM fo_advert_completions WHERE completion_id=$1 AND player_id=$2 AND placement='match3-double' AND match_id=$3 RETURNING completion_id`,[advertCompletionId,playerId,sessionId]);if(!ad.rowCount)throw Object.assign(new Error('Verified advert completion required'),{status:403,code:'ADVERT_NOT_VERIFIED'});await appendCoinTransaction(client,{accountId:playerId,transactionId:tx,amount:MATCH3_ADVERT_COIN_BONUS,transactionType:'promotional-grant',sourceReferenceId:advertCompletionId,metadata:{source:'match3-advert-double',sessionId,levelId:row.level_id},allowCreation:true});await client.query(`UPDATE fo_match3_sessions SET advert_stars_granted=TRUE WHERE session_id=$1`,[sessionId]);await client.query('COMMIT');return{duplicate:false,coinsGranted:MATCH3_ADVERT_COIN_BONUS,totalCoins:MATCH3_BASE_COIN_REWARD+MATCH3_ADVERT_COIN_BONUS,reward:{currencyId:'coins',amount:MATCH3_ADVERT_COIN_BONUS},transactionId:tx}}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
export const doubleMatch3Stars = doubleMatch3Coins
